# Generated by Django 5.2.17 on 2026-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chg_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('chg_name', models.CharField(max_length=255)),
                ('chg_description', models.TextField(blank=True, null=True)),
                ('chg_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Characteristic group',
                'verbose_name_plural': 'Characteristic groups',
                'db_table': 'characteristics_group',
                'ordering': ['chg_name'],
            },
        ),
    ]
