# Generated by Django 5.2.17 on 2026-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicgroup',
            name='chg_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='chg_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='chg_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='chg_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='chg_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='chg_name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
