# Generated by Django 5.2.17 on 2026-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_characteristicgroup_chg_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unt_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('unt_name', models.CharField(max_length=255)),
                ('unt_name_en', models.CharField(max_length=255, null=True)),
                ('unt_name_ru', models.CharField(max_length=255, null=True)),
                ('unt_name_uk', models.CharField(max_length=255, null=True)),
                ('unt_symbol', models.CharField(max_length=20)),
                ('unt_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'characteristics_unit',
                'ordering': ['unt_name'],
            },
        ),
    ]
