# Generated by Django 5.2.17 on 2026-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='chg_status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unt_symbol',
            field=models.CharField(max_length=20, verbose_name='Symbol'),
        ),
    ]
