# Generated by Django 5.2.17 on 2026-09-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='prices.currency'),
        ),
    ]
