# Generated by Django 5.2.17 on 2026-09-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productdocumentation_productimage_assemblycomponent'),
        ('prices', '0007_price_ck_price_valid_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='catalog.product')),
            ],
            options={
                'db_table': 'prices_discount',
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='ck_discount_value_positive'), models.CheckConstraint(condition=models.Q(('type__in', ('percent', 'fixed'))), name='ck_discount_type_valid'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='ck_discount_valid_period'), models.CheckConstraint(condition=models.Q(models.Q(('type', 'percent'), ('value__lte', 100)), ('type', 'fixed'), _connector='OR'), name='ck_discount_percent_max')],
            },
        ),
    ]
