# Generated by Django 5.2.17 on 2026-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_color_alter_product_color_seriescolor_typecolor'),
        ('prices', '0008_discount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='ck_discount_valid_period',
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='ck_discount_valid_period_discount'),
        ),
    ]
