# Generated by Django 5.2.17 on 2026-09-09 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_is_discontinued'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порог малого остатка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Политика остатков',
                'verbose_name_plural': 'Политики остатков',
                'db_table': 'stock_policy',
            },
        ),
    ]
