# Generated by Django 5.2.17 on 2026-09-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_ck_product_stock_quantity_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('reference', 'Reference'), ('number', 'Number'), ('boolean', 'Boolean'), ('text', 'Text')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_characteristic',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.characteristic')),
            ],
            options={
                'db_table': 'catalog_characteristic_value',
                'ordering': ('characteristic', 'value'),
            },
        ),
        migrations.CreateModel(
            name='ExecutionCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_characteristics', to='catalog.characteristic')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.execution')),
                ('value_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_characteristics', to='catalog.characteristicvalue')),
            ],
            options={
                'db_table': 'catalog_execution_characteristic',
            },
        ),
        migrations.CreateModel(
            name='ModelCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_characteristics', to='catalog.characteristic')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.model')),
                ('value_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_characteristics', to='catalog.characteristicvalue')),
            ],
            options={
                'db_table': 'catalog_model_characteristic',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristics', to='catalog.characteristic')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.product')),
                ('value_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_characteristics', to='catalog.characteristicvalue')),
            ],
            options={
                'db_table': 'catalog_product_characteristic',
            },
        ),
        migrations.CreateModel(
            name='TypeCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_characteristics', to='catalog.characteristic')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.type')),
                ('value_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_characteristics', to='catalog.characteristicvalue')),
            ],
            options={
                'db_table': 'catalog_type_characteristic',
            },
        ),
        migrations.AddConstraint(
            model_name='characteristicvalue',
            constraint=models.UniqueConstraint(fields=('characteristic', 'value'), name='uq_characteristic_value'),
        ),
        migrations.AddConstraint(
            model_name='executioncharacteristic',
            constraint=models.UniqueConstraint(fields=('execution', 'characteristic'), name='uq_execution_characteristic'),
        ),
        migrations.AddConstraint(
            model_name='modelcharacteristic',
            constraint=models.UniqueConstraint(fields=('model', 'characteristic'), name='uq_model_characteristic'),
        ),
        migrations.AddConstraint(
            model_name='productcharacteristic',
            constraint=models.UniqueConstraint(fields=('product', 'characteristic'), name='uq_product_characteristic'),
        ),
        migrations.AddConstraint(
            model_name='typecharacteristic',
            constraint=models.UniqueConstraint(fields=('type', 'characteristic'), name='uq_type_characteristic'),
        ),
    ]
