# Generated by Django 5.2.17 on 2026-09-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productdocumentation_productimage_assemblycomponent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='ck_product_stock_quantity_non_negative',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
