# Generated by Django 5.2.17 on 2026-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_color_product_protection_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
