# Generated by Django 5.2.17 on 2026-09-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_characteristic_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.color'),
        ),
        migrations.CreateModel(
            name='SeriesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_colors', to='catalog.color')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_colors', to='catalog.series')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('series', 'color'), name='uq_series_color')],
            },
        ),
        migrations.CreateModel(
            name='TypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_colors', to='catalog.color')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_colors', to='catalog.type')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'color'), name='uq_type_color')],
            },
        ),
    ]
