# Generated by Django 5.2.17 on 2026-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_name_en', models.CharField(max_length=255, null=True)),
                ('cat_name_ru', models.CharField(max_length=255, null=True)),
                ('cat_name_uk', models.CharField(max_length=255, null=True)),
                ('cat_description', models.TextField(blank=True, null=True)),
                ('cat_description_en', models.TextField(blank=True, null=True)),
                ('cat_description_ru', models.TextField(blank=True, null=True)),
                ('cat_description_uk', models.TextField(blank=True, null=True)),
                ('cat_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'common_category',
                'ordering': ('cat_name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('grp_name', models.CharField(max_length=255)),
                ('grp_name_en', models.CharField(max_length=255, null=True)),
                ('grp_name_ru', models.CharField(max_length=255, null=True)),
                ('grp_name_uk', models.CharField(max_length=255, null=True)),
                ('grp_description', models.TextField(blank=True, null=True)),
                ('grp_description_en', models.TextField(blank=True, null=True)),
                ('grp_description_ru', models.TextField(blank=True, null=True)),
                ('grp_description_uk', models.TextField(blank=True, null=True)),
                ('grp_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'common_group',
                'ordering': ('grp_name',),
            },
        ),
    ]
