# Generated by Django 5.2.17 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brd_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('brd_name', models.CharField(max_length=255)),
                ('brd_name_en', models.CharField(max_length=255, null=True)),
                ('brd_name_ru', models.CharField(max_length=255, null=True)),
                ('brd_name_uk', models.CharField(max_length=255, null=True)),
                ('brd_description', models.TextField(blank=True, null=True)),
                ('brd_description_en', models.TextField(blank=True, null=True)),
                ('brd_description_ru', models.TextField(blank=True, null=True)),
                ('brd_description_uk', models.TextField(blank=True, null=True)),
                ('brd_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'common_brand',
                'ordering': ('brd_name',),
            },
        ),
    ]
