# Generated by Django 5.2.17 on 2026-10-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('ser_name', models.CharField(max_length=255)),
                ('ser_description', models.TextField(blank=True, null=True)),
                ('ser_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='common.brand')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'db_table': 'common_series',
                'ordering': ('ser_name',),
            },
        ),
    ]
