# Generated by Django 5.2.17 on 2026-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='ser_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='ser_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='ser_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='ser_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='ser_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='ser_name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
