# Generated by Django 5.2.17 on 2026-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_series_ser_description_en_series_ser_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('typ_name', models.CharField(max_length=255)),
                ('typ_name_en', models.CharField(max_length=255, null=True)),
                ('typ_name_ru', models.CharField(max_length=255, null=True)),
                ('typ_name_uk', models.CharField(max_length=255, null=True)),
                ('typ_description', models.TextField(blank=True, null=True)),
                ('typ_description_en', models.TextField(blank=True, null=True)),
                ('typ_description_ru', models.TextField(blank=True, null=True)),
                ('typ_description_uk', models.TextField(blank=True, null=True)),
                ('typ_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'common_type',
                'ordering': ('typ_name',),
            },
        ),
    ]
