# Generated by Django 5.2.17 on 2026-10-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_types', to='common.group')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_types', to='common.type')),
            ],
            options={
                'verbose_name': 'Group type',
                'verbose_name_plural': 'Group types',
                'db_table': 'common_group_type',
                'constraints': [models.UniqueConstraint(fields=('group', 'type'), name='unique_group_type')],
            },
        ),
    ]
