# Generated by Django 5.2.17 on 2026-10-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_grouptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_types', to='common.series')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_types', to='common.type')),
            ],
            options={
                'verbose_name': 'Series type',
                'verbose_name_plural': 'Series types',
                'db_table': 'common_series_type',
                'constraints': [models.UniqueConstraint(fields=('series', 'type'), name='unique_series_type')],
            },
        ),
    ]
