# Generated by Django 5.2.17 on 2026-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_seriestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptd_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('ptd_name', models.CharField(max_length=255)),
                ('ptd_description', models.TextField(blank=True, null=True)),
                ('ptd_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protection degree',
                'verbose_name_plural': 'Protection degrees',
                'db_table': 'common_protection_degree',
                'ordering': ('ptd_name',),
            },
        ),
    ]
