# Generated by Django 5.2.17 on 2026-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_protectiondegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectiondegree',
            name='ptd_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protectiondegree',
            name='ptd_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protectiondegree',
            name='ptd_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
