# Generated by Django 5.2.17 on 2026-10-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_protectiondegree_ptd_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clr_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('clr_name', models.CharField(max_length=255)),
                ('clr_description', models.TextField(blank=True, null=True)),
                ('clr_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'common_color',
                'ordering': ('clr_name',),
            },
        ),
    ]
