# Generated by Django 5.2.17 on 2026-10-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='clr_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='clr_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='clr_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='clr_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='clr_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='clr_name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
