# Generated by Django 5.2.17 on 2026-10-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_color_clr_description_en_color_clr_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_series', to='common.color')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_colors', to='common.series')),
            ],
            options={
                'verbose_name': 'Series product color',
                'verbose_name_plural': 'Series product colors',
                'db_table': 'common_series_product_color',
                'constraints': [models.UniqueConstraint(fields=('series', 'color'), name='unique_series_product_color')],
            },
        ),
    ]
