# Generated by Django 5.2.17 on 2026-10-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_seriesproductcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesFrameColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_series', to='common.color')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_colors', to='common.series')),
            ],
            options={
                'verbose_name': 'Series frame color',
                'verbose_name_plural': 'Series frame colors',
                'db_table': 'common_series_frame_color',
                'constraints': [models.UniqueConstraint(fields=('series', 'color'), name='unique_series_frame_color')],
            },
        ),
    ]
