# Generated by Django 5.2.17 on 2026-10-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_seriesframecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('mdl_name', models.CharField(max_length=255)),
                ('mdl_description', models.TextField(blank=True, null=True)),
                ('mdl_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type model',
                'verbose_name_plural': 'Type models',
                'db_table': 'common_type_model',
                'ordering': ('mdl_name',),
            },
        ),
        migrations.CreateModel(
            name='TypeModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='common.type')),
                ('type_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_links', to='common.typemodel')),
            ],
            options={
                'verbose_name': 'Type model type',
                'verbose_name_plural': 'Type model types',
                'db_table': 'common_type_model_type',
                'constraints': [models.UniqueConstraint(fields=('type_model', 'type'), name='unique_type_model_type')],
            },
        ),
    ]
