# Generated by Django 5.2.17 on 2026-10-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_typemodel_mdl_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exc_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('exc_name', models.CharField(max_length=255)),
                ('exc_description', models.TextField(blank=True, null=True)),
                ('exc_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
                'db_table': 'common_execution',
                'ordering': ('exc_name',),
            },
        ),
        migrations.CreateModel(
            name='TypeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_links', to='common.execution')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_links', to='common.type')),
            ],
            options={
                'verbose_name': 'Type execution',
                'verbose_name_plural': 'Type executions',
                'db_table': 'common_type_execution',
                'constraints': [models.UniqueConstraint(fields=('type', 'execution'), name='unique_type_execution')],
            },
        ),
    ]
