# Generated by Django 5.2.17 on 2026-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordernumbersequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumbersequence',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
