# Generated by Django 5.2.17 on 2026-09-09 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_available',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_incoming',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ожидается'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_on_order',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Заказано поставщику'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарезервировано'),
        ),
    ]
