# Generated by Django 5.2.17 on 2026-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_quantity_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_discontinued',
            field=models.BooleanField(default=False, verbose_name='Снят с продажи'),
        ),
    ]
