# Generated by Django 5.2.17 on 2026-09-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_currency'),
        ('prices', '0008_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='prices.currency'),
        ),
    ]
