# Generated by Django 5.2.17 on 2026-09-22 12:47

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_color_alter_product_color_seriescolor_typecolor'),
        ('orders', '0003_alter_order_currency'),
        ('prices', '0010_orderdiscount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='ck_order_subtotal_positive',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ck_order_discount_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ck_order_total_positive',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ck_order_discount_lte_subtotal',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='ck_order_item_total_positive',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='ck_order_item_discount_lte_subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_total',
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='product_discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='ck_order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('product_discount_total__gte', 0)), name='ck_order_product_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('order_discount__gte', 0)), name='ck_order_order_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_discount__gte', 0)), name='ck_order_promotion_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('order_discount__gte', 0), ('promotion_discount__gte', 0), ('order_discount__lte', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('promotion_discount')))), name='ck_order_final_discount_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_order_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_order_item_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('unit_price'))), name='ck_order_item_discount_lte_unit_price'),
        ),
    ]
