# Generated by Django 5.2.17 on 2026-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_exchange_rate_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='ck_order_number_sequence_nonnegative')],
            },
        ),
    ]
