# Generated by Django 5.2.17 on 2026-09-29 08:10

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_ck_order_final_discount_lte_subtotal_and_more'),
        ('prices', '0011_exchangerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='ck_order_final_discount_lte_subtotal',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('order_discount__gte', 0), ('promotion_discount__gte', 0), ('order_discount__lte', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('promotion_discount')))), name='ck_order_final_discount_lte_subtotal'),
        ),
    ]
