# Generated by Django 5.2.17 on 2026-09-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, unique=True)),
                ('packaging', models.TextField(blank=True, null=True)),
                ('sales_unit', models.CharField(max_length=50)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_name', models.TextField(blank=True, null=True)),
                ('manufacturer_description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.execution')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.group')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.model')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.series')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.type')),
            ],
            options={
                'db_table': 'catalog_product',
            },
        ),
    ]
