# Generated by Django 5.2.17 on 2026-09-07 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_characteristic_characteristicvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_documentation',
                'ordering': ('product', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_image',
                'ordering': ('product', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('assembly_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_components', to='catalog.product')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_assemblies', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_assembly_component',
                'constraints': [models.UniqueConstraint(fields=('assembly_product', 'component_product'), name='uq_assembly_component'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_assembly_component_quantity_positive')],
            },
        ),
    ]
