# Generated by Django 5.2.17 on 2026-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_ck_product_stock_quantity_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='protection_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
