# Generated by Django 5.2.17 on 2026-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_date_created_category_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('cat_name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='cat_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_en',
            new_name='cat_description_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_ru',
            new_name='cat_description_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_uk',
            new_name='cat_description_uk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='cat_name_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='cat_name_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_uk',
            new_name='cat_name_uk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='cat_status',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
