# Generated by Django 5.2.17 on 2026-09-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
