# Generated by Django 5.2.17 on 2026-09-30 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_category_cat_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('grp_name',), 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='grp_name',
        ),
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='grp_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='grp_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='grp_status',
            field=models.BooleanField(default=True),
        ),
    ]
