# Generated by Django 5.2.17 on 2026-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_group_options_rename_name_group_grp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grp_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
