# Generated by Django 5.2.17 on 2026-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_group_grp_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('brd_name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brd_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='brd_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brd_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brd_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
