# Generated by Django 5.2.17 on 2026-10-01 12:10
# Generated by Django 5.2.17 on 2026-10-01 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_rename_model_to_typemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={
                "ordering": ("srs_name",),
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
            },
        ),

        migrations.RemoveConstraint(
            model_name="modelcharacteristic",
            name="uq_model_characteristic",
        ),

        migrations.RenameField(
            model_name="series",
            old_name="name",
            new_name="srs_name",
        ),

        migrations.AddField(
            model_name="series",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="series",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AddField(
            model_name="series",
            name="srs_code",
            field=models.CharField(
                default=1,
                editable=False,
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="series",
            name="srs_description",
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="series",
            name="srs_status",
            field=models.BooleanField(default=True),
        ),

        migrations.AlterField(
            model_name="series",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="catalog.brand",
            ),
        ),

        migrations.AddConstraint(
            model_name="modelcharacteristic",
            constraint=models.UniqueConstraint(
                fields=("typemodel", "characteristic"),
                name="uq_model_characteristic",
            ),
        ),

        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("brand", "srs_name"),
                name="uq_series_brand_name",
            ),
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="brand",
                    name="brd_code",
                    field=models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="brand",
                    name="date_created",
                    field=models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="brand",
                    name="date_updated",
                    field=models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="typemodel",
                    name="type",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_models",
                        to="catalog.type",
                    ),
                ),
                migrations.AlterModelTable(
                    name="typemodel",
                    table="catalog_type_model",
                ),
            ],
        ),
    ]

