# Generated by Django 5.2.17 on 2026-10-01 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_series_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('typ_name',), 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.AddField(
            model_name='type',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='type',
            name='typ_code',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='typ_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='typ_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='typ_status',
            field=models.BooleanField(default=True),
        ),
    ]
