# Generated by Django 5.2.17 on 2026-10-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_type_options_remove_type_name_and_more"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="product",
                    name="category",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="common.category",
                    ),
                ),
                migrations.AlterField(
                    model_name="categorygroup",
                    name="category",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_groups",
                        to="common.category",
                    ),
                ),
                migrations.AlterField(
                    model_name="product",
                    name="group",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="common.group",
                    ),
                ),
                migrations.AlterField(
                    model_name="categorygroup",
                    name="group",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_groups",
                        to="common.group",
                    ),
                ),
                migrations.DeleteModel(
                    name="Category",
                ),
                migrations.DeleteModel(
                    name="Group",
                ),
            ],
        ),
    ]
