# Generated by Django 5.2.17 on 2026-09-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_productdocumentation_productimage_assemblycomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.product')),
            ],
            options={
                'db_table': 'prices_price',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_price_amount_positive')],
            },
        ),
    ]
