# Generated by Django 5.2.17 on 2026-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
