# Generated by Django 5.2.17 on 2026-09-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_price_valid_from_price_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
