# Generated by Django 5.2.17 on 2026-09-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productdocumentation_productimage_assemblycomponent'),
        ('prices', '0006_alter_price_valid_from'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='ck_price_valid_period'),
        ),
    ]
