# Generated by Django 5.2.17 on 2026-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_remove_discount_ck_discount_valid_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prices_order_discount',
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='ck_order_discount_value_positive'), models.CheckConstraint(condition=models.Q(('type__in', ('percent', 'fixed'))), name='ck_order_discount_type_valid'), models.CheckConstraint(condition=models.Q(models.Q(('type', 'percent'), ('value__lte', 100)), ('type', 'fixed'), _connector='OR'), name='ck_order_discount_percent_max'), models.CheckConstraint(condition=models.Q(('min_order_amount__gte', 0)), name='ck_order_discount_min_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('max_order_amount__isnull', True), ('max_order_amount__gt', models.F('min_order_amount')), _connector='OR'), name='ck_order_discount_amount_range'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='ck_order_discount_valid_period')],
            },
        ),
    ]
