# Generated by Django 5.2.17 on 2026-09-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0010_orderdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('valid_from', models.DateTimeField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_base', to='prices.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_quote', to='prices.currency')),
            ],
            options={
                'db_table': 'prices_exchange_rate',
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='ck_exchange_rate_positive'), models.CheckConstraint(condition=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='ck_exchange_rate_different_currencies'), models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'valid_from'), name='uq_exchange_rate_period')],
            },
        ),
    ]
